### ISSUE TITLE
Recommend Stable Release Docker Tags Instead of :latest

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/documentation#103]
Hi all,

The :latest docker tag is risky as it can have bugs from latest master that are not yet proven stable. Instead, we should be recommending the latest stable release. Maybe we can create a :stable docker tag which utilizes the latest release for Prysm for both the beacon node and the validator.

**Comment by stefa2k** [comment]
I'd love to see a tag named like the release, so I can jump back too. Something on the lines of "alpha.6" and "alpha.7" as tags for both, the validator and the beacon node.

Tag "stable" is also a very good idea to point to the latest stable release.

**Comment by stefa2k** [comment]
There are still no `:stable` tag nor `alpha.11` tags for docker images.
