### ISSUE TITLE
Add Some System / Hardware Reqs to Docs Page

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/documentation#120]
Hi @har00ga this is an issue to add some system requirements to installing Prysm in our docs portal. Currently, we tell people to visit our medium post https://medium.com/prysmatic-labs/introducing-topaz-testnet-8e8a4e00a700 but would be best to have the reqs at the top of each install page

**Comment by har00ga** [comment]
The sys requirements are currently on the script pages, but will replicate on the Docker & Bazel ones too :)
