### ISSUE TITLE
Grafana dashboard links not working

### ISSUE THREAD

**Issue by c-kr** [prysmaticlabs/documentation#124]
The new links to the grafana dashboards do not seem to work.

https://github.com/prysmaticlabs/documentation/commit/24be1f8346e84e0670bbbe673b6581c3cba8e0f3

**Comment by prestonvanloon** [comment]
![IMG_2886](https://user-images.githubusercontent.com/7246818/82917528-64fc8380-9f28-11ea-9648-db04cea55a8b.jpg)

CC @GuillaumeMiralles

**Comment by GuillaumeMiralles** [comment]
Hey yes sorry for this. I tagged @har00ga about it on discord already.
For the time being, @c-kr r you can find the link here until we get this fixed
https://github.com/GuillaumeMiralles/prysm-grafana-dashboard

**Comment by har00ga** [comment]
#127
