### ISSUE TITLE
Request: Add documentation about file based configuration

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/documentation#13]
New functionality has been added to Prysm to support loading flag values from a yaml file. https://github.com/prysmaticlabs/prysm/pull/4878

The usage is straightforward, you may create a yaml file as a simple key value representation of the flags you wish to provide.

For example, if we usually run with `--datadir=/data --enable-ssz-cache` we could create a file like

```yaml
datadir: "/data"
enable-ssz-cache: true
```

Then the user would provide the runtime flag to Prysm of `--config-file=/path/to/file.yaml` along with any other runtime flags they wish.

An important note is that flags via command line and via config file can both be present but the config file has the priority. In other words, if we set the flag `--datadir=/data2` and `datadir: "/data1"` in the config.yaml file, Prysm would understand that it should write to `/data1`. 

Please add this documentation to the website and any relevant markdown in Prysm. Thanks

**Comment by har00ga** [comment]
961beda Merged!
