### ISSUE TITLE
New Guide: Security Best Practices for running a validator

### ISSUE THREAD

**Issue by wgknowles** [prysmaticlabs/documentation#136]
As we approach the launch of mainnet, the risks involved with running a validator node are starting to become real.  A practical guide with actionable risk-prioritised best practices and recommendations would be an excellent resource that may save a number of people from having a very bad day by losing their hard earned ETH.

This guide should cover much more then just "how to not get hacked".  Issues as simple as losing funds due to crashed hard drives, forgotten passwords, or accidentally deleted keys are arguably more common then getting pwned.

Please add your ideas for topics below.  This guide will likely be an on-going effort requiring input from multiple experts before it reaches a level of maturity with good coverage of how to manage risks spanning confidentiality integrity and availability.

**Comment by har00ga** [comment]
This is actually a highly documented topic covered in a number of related tech, the Tor one comes to mind first: https://trac.torproject.org/projects/tor/wiki/doc/TorRelaySecurity . Shouldn't be anything overly fancy that needs to be compiled outside of normal secure storage / OS protocol

**Comment by har00ga** [comment]
#129

**Comment by har00ga** [comment]
Just a note, already working on this and should be ready for review later this week
