### ISSUE TITLE
 missing dependencies #10 

### ISSUE THREAD

**Issue by q9f** [prysmaticlabs/documentation#188]
even though bazel does fetch most of the dependencies, on a fresh ubuntu 20.04 machine, I had to manually install the following packages before I was able to run `bazel build`

```
apt install libgmp-dev libtinfo5
```

**Comment by prestonvanloon** [comment]
This is required for `--config=release`, we also need to add openssl as a system dependency. 

It would be a good idea to try a release build from a new server to see what system dependencies are expected for a release build.

**Comment by q9f** [comment]
> It would be a good idea to try a release build from a new server to see what system dependencies are expected for a release build.

I just tried and missed `libgmp-dev libtinfo5 libssl-dev` (but on that note, the server had `build-essential` and `bazel`)
