### ISSUE TITLE
General search returns results that leads to Page Not Found

### ISSUE THREAD

**Issue by metanull-operator** [prysmaticlabs/documentation#190]
I wanted to find any documentation on exiting a validator to share with someone on Discord.

Went to https://docs.prylabs.network/docs/getting-started/

Entered "exit" into search in the upper right corner and got the following:

![image](https://user-images.githubusercontent.com/54516310/87813469-352e7580-c81f-11ea-9360-d1aac757886f.png)

Clicked on outlined link in screenshot, and got a Page Not Found error.

![image](https://user-images.githubusercontent.com/54516310/87813523-49727280-c81f-11ea-96ef-de9e69cbfea2.png)

**Comment by prestonvanloon** [comment]
Looks like a configuration setting where `/docs` prefix is duplicated. Example:
```
https://docs.prylabs.network/docs/docs/prysm-usage/wallet-keymanager/#exiting-a-validator
```

**Comment by rkapka** [comment]
Same thing happens with typing `gRPC`. There is a `Securing your gRPC connections` search result that leads to a non-existing page. I don't think this is merely a duplicated prefix issue as removing the duplication in the gRPC returns a 404 as well: https://docs.prylabs.network/docs/prysm-usage/secure-grpc/
What's more interesting is that the non-duplicated prefix link returns a generic nginx 404 page.

**Comment by terencechain** [comment]
@rhlsthrm just reported to me as well. This happens to all the results.

**Comment by har00ga** [comment]
Seach issue is solved, closing
