### ISSUE TITLE
docs.prylabs.network returns 404

### ISSUE THREAD

**Issue by LarsHolte** [prysmaticlabs/documentation#195]
URL from the About section in [https://github.com/prysmaticlabs/documentation](https://github.com/prysmaticlabs/documentation) to [docs.prylabs.network](https://docs.prylabs.network) returns not found 404.

Should redirect to [https://docs.prylabs.network/docs/getting-started](https://docs.prylabs.network/docs/getting-started) ?

**Comment by prestonvanloon** [comment]
I think this has been fixed. Please let me know if not. I wasn't able to reproduce after a recent change to some config.
