### ISSUE TITLE
Open port 13000 for p2p connections when using docker

### ISSUE THREAD

**Issue by KuDeTa** [prysmaticlabs/documentation#2]
In order to get incoming connections from peers, port 13000 should be open from router/firewall to host.

If running on docker, present instructions say

docker run -it -v $HOME/prysm/beacon:/data -p 4000:4000
gcr.io/prysmaticlabs/prysm/beacon-chain:latest
--datadir=/data

Please add -p 13000:13000 to enable docker host to forward 13000 to container appropriately.

**Comment by har00ga** [comment]
Thanks for moving to this repo, keeps things much more organised. :slightly_smiling_face: I'll make this update tonight.

**Comment by har00ga** [comment]
Implemented: 878ddd3

**Comment by icemagno** [comment]
Wich container?
Geth, Validator or Beacon ?
