### ISSUE TITLE
docs/install/arm.md and linux.md and mac.md have broken link / 404

### ISSUE THREAD

**Issue by chrishobcroft** [prysmaticlabs/documentation#21]
`docs/install/arm.md`, `docs/install/linux.md` and `docs/install/mac.md` all link to:

https://docs.prylabs.network/docs/install/prysm-usage/parameters

![Screenshot from 2020-04-06 12-21-27](https://user-images.githubusercontent.com/2212651/78530446-4835b080-7801-11ea-8291-79b9aca7c3c7.png)

But this link gives a 404.

![Screenshot from 2020-04-06 12-21-55](https://user-images.githubusercontent.com/2212651/78530434-44099300-7801-11ea-9ab3-315f13c15be4.png)

**Comment by har00ga** [comment]
Thanks a ton :) Will resolve this today.
