### ISSUE TITLE
Guide: Migrating Keys Between Eth2 Clients or Between Machines

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/documentation#224]
This is a high priority item for us before we go to mainnet. We need to have detailed documentation regarding migrating validator keys between eth2 clients safely. Although different eth2 clients have various ways of representing keys, we all follow the common EIP-2335 standard for keystore.json files to store secrets. Migrating keys is not an easy feat, as you also need to migrate [`slashing protection histories`](https://hackmd.io/@sproul/Bk0Y0qdGD) which is still a work in progress. We should aim to include the following in this documentation:
- A preface on how Prysm handles validator keys
- How to backup your keys and delete them from Prysm
- How to import keys from an external source, such as from a backup generated by lighthouse's eth2 client
- How to import keys in other eth2 clients (might be tough as if they change their code, our docs become stale)
- How to export your validating history for slashing protection purposes (work in progress)

**Comment by michaelsproul** [comment]
Just dropping by to note that EIP-3076 is out now, which replaces the linked slashing protection spec

https://eips.ethereum.org/EIPS/eip-3076

**Comment by slavik0329** [comment]
Any updates on this?

**Comment by kathekon** [comment]
Checking in.  Is this still in the works?  Or does [this](https://docs.prylabs.network/docs/prysm-usage/database-backups)doc on backups essentially address the issue?  Or perhaps I'm confused? :-)
