### ISSUE TITLE
Add Documentation for Error Codes in Prysm

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/documentation#226]
As part of mainnet, we will revamp Prysm's error handling to use specific error codes in logs when something goes wrong. For example, instead of seeing `ERROR: attestation did not verify`, users will see `ERROR: code 402 Attestation did not verify` where they can look up that error code in our documentation and understand it better. We are working on this error code revamp and it will require a detailed page in our docs for each error code.

**Comment by rkapka** [comment]
Assigning myself as this should be a part of the error handling revamp feature.

**Comment by rauljordan** [comment]
We have decided as a team this is not the best use of time and can add some extra complexity
