### ISSUE TITLE
Add instructions to run local ETH1 / goerli node

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/documentation#23]
These instructions should be part of the recommended setup. 

Soon, Prysmatic Labs will start discouraging use of their hosted ETH1 nodes so the documentation should reflect a user path for operating a ETH1 node.

Suggested format / paths:

- Run your own ETH1 goerli node (RECOMMENDED)
- Connect to a hosted node, provide a link to infura and provide the flags to connect to Prysm's nodes.

The recommended path is to reduce the centralization risk and mimic a more realistic scenario. Prysm will continue to provide a public ETH1 node for ease of use but users should strongly consider running their own ETH1 node if they are running a beacon node and validator.

**Comment by prestonvanloon** [comment]
A few notes:
- We recently removed the websockets requirement for eth1 https://github.com/prysmaticlabs/prysm/pull/6055
-  Beaconcha.in has a good [guide](https://kb.beaconcha.in/run-a-goerli-node-eth1-and-beaconnode-eth2) that might be a starting point. We'd like to add instructions or support for geth _and_ nethermind if possible.

**Comment by rauljordan** [comment]
Done by #145
