### ISSUE TITLE
Remove Usage of "You" From Documentation

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/documentation#232]
This is a tracking issue to remove all imperative, "you" tone from the documentation content, as it is not best practice and makes the documentation more informal. We should replace with "one" where appropriate or remove the imperative tone in certain places as needed. cc @har00ga

**Comment by har00ga** [comment]
I should have time to look at this next week, it's a good idea. :slightly_smiling_face:

**Comment by rauljordan** [comment]
This is so low priority and not as important compared to other action items. We will just make sure to follow the appropriate tone from now on when writing more docs, closing
