### ISSUE TITLE
Separate development and production environments

### ISSUE THREAD

**Issue by rkapka** [prysmaticlabs/documentation#238]
Right now we are shipping directly to production after merging to master, like a boss. Unfortunately sometimes functionality that works locally breaks on the server. We should have a separate dev environment so that we can verify our changes before making them public. This should be done in the form of a deploy pipeline:
1. Merge to master
2. Deploy to dev (automatic)
3. Deploy to prod (manual)

**Comment by har00ga** [comment]
> like a boss

+1

**Comment by prestonvanloon** [comment]
We can do this, but we need to decide how often we complete manual pushes to prod. We had a similar setup for the testnet site but core-team was getting pinged to push to prod very frequently.

**Comment by rkapka** [comment]
We could also prepare a canary or some simple check that would verify response codes before making the release. Just a sanity check for 200 OK should be enough for now. I can try adding this to the Spinnaker pipeline.

What do you think @prestonvanloon?

**Comment by har00ga** [comment]
Related: https://docusaurus.io/docs/en/versioning
