### ISSUE TITLE
Outdated, deprecated startup parameters

### ISSUE THREAD

**Issue by Djadih** [prysmaticlabs/documentation#246]
**It seems that this documentation page is out of date with the latest prysm versions.**

https://docs.prylabs.network/docs/prysm-usage/parameters#beacon-node-parameters

- "--web3provider" is deprecated but still listed as a flag, next to its successor "--http-web3provider". This specific issue probably existed since as long ago as May 12, when this issue removed one of them.
https://github.com/prysmaticlabs/prysm/issues/5826

**Comment by MysticRyuujin** [comment]
I'm also curious / concerned about the `--disable-accounts-v2` flag and how long that flag will be available. It's currently undocumented as well.

Using `ethdo` with the `--keymanager=wallet` and `--keymanageropts=/data/config/keymanager.json` flags is working today using that flag, but I'm concerned it will suddenly not work in a future update, and what I should do about it, if anything. If the flag is to remain available for the foreseeable future I'd like to know.

**Comment by rauljordan** [comment]
@MysticRyuujin we will deprecate old features as part of our beta release coming this month, and there will be detailed documentation on upgrading to Prysm beta. We typically never do breaking updates during alpha for the same concerns you mentioned. We will also publish ahead of time a blog post regarding our beta release and what stakers can expect. This beta release will be close to what users can expect in mainnet in terms of configuration options
