### ISSUE TITLE
Datadir no longer needed

### ISSUE THREAD

**Issue by dagohbah** [prysmaticlabs/documentation#253]
In step 5 of the doc below, for the validator docker setup instructions:
https://docs.prylabs.network/docs/testnet/medalla

The "--datadir=/validatorDB" flag is no longer needed, and is creating an error if you try to include it when running this command in. Also, the account-v2 portion is also not working, but just "account" is.

Here are the errors:
ERROR main: could not open wallet: no wallet found, create a new one with validator wallet create
Incorrect Usage: flag provided but not defined: -datadir
ERROR main: flag provided but not defined: -datadir

Thanks!

**Comment by rauljordan** [comment]
No longer relevant as we changed this functionality since a long time
