### ISSUE TITLE
windows install step1 -2.fetch the prysm.bat script from GIthub .PROBLEM is:curl: (6) Could not resolve host: raw.githubusercontent.com

### ISSUE THREAD

**Issue by navy665180** [prysmaticlabs/documentation#290]
install step1 -2.fetch the prysm.bat script from GIthub .PROBLEM is:curl: (6) Could not resolve host: raw.githubusercontent.com
I installed  Git-2.29.2.2-64-bit ,first. the system i build just now ,win10 pro x64.
what shall i do?

**Comment by har00ga** [comment]
This was very likely caused either by an issue with Github's server, or your individual network configuration. If you are still unable to perform this action today, I'd check your firewall settings. As such, I'm closing this ticket.
