### ISSUE TITLE
Cannot access neither metrics nor web on the validator container

### ISSUE THREAD

**Issue by 0x6431346e** [prysmaticlabs/documentation#294]
This is what I'm doing:

```
docker run -it --name validator -v Z:\Eth2Validators\prysm-wallet-v2:/wallet -v Z:\Eth2:/validatorDB --network="host" -p 8281:8281 -p 7500:7500 gcr.io/prysmaticlabs/prysm/validator:stable --beacon-rpc-provider=127.0.0.1:4000 --wallet-dir=/wallet --datadir=/validatorDB --monitoring-host=0.0.0.0 --monitoring-port 8281 --web
```

but I cannot access the web portal nor `localhost:8281/metrics`. (connection refused)

FWIW: the beacon monitoring, `localhost:8080/metrics`, **does** work...so, my guess is that it has something to do with the `--network="host"` flag..

**Comment by rauljordan** [comment]
Hi @0x6431346e this is something best discussed on discord so we can get more details about your particular issue, please let us know: https://discord.gg/prysmaticlabs
