### ISSUE TITLE
When exporting slashing protection data, clarify what to use for `--datadir`

### ISSUE THREAD

**Issue by chrishobcroft** [prysmaticlabs/documentation#365]
Currently, the documentation suggests the following command to export slashing protection data using the Prysm installation script:
```
prysm.sh validator slashing-protection export --datadir=/path/to/your/wallet --slashing-protection-export-dir=/path/to/desired/outputdir
```

The value for `--datadir` is ambiguous.

Per @nisdas comment in Discord, this should refer to the directory containing the `validator.db`, which e.g. defaults to `~/.eth2validators/prysm-wallet-v2/direct` on Linux.

It could be made much clearer, to provide less friction when switching clients.

**Comment by symbolpunk** [comment]
Thanks for submitting these issues folks, closing as fixed.
