### ISSUE TITLE
Add system specification requirements

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/documentation#38]
We recently published recommended system requirements. These would be helpful to have somewhere in the docs pages.

https://medium.com/prysmatic-labs/introducing-topaz-testnet-8e8a4e00a700

**Comment by har00ga** [comment]
Partially implemented now on the script pages with #43, if you guys are cool with that format I will replicate it throughout the Docker and Bazel documents as well

**Comment by har00ga** [comment]
As per our discord convo this is being populated on the final pages in my next PR
