### ISSUE TITLE
Add Grafana/Prometheus Information

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/documentation#44]
This is a tracking issue to add information regarding visualizing a local node's metrics via a Grafana dashboard. We should create a page called Visualizing Node Metrics that suggests users to use the following dashboard: https://www.dropbox.com/s/9mqsvm1s0jmzu98/Prysm%20Dashboard-1587566218430.json?dl=0. Nodes run prometheus metrics by default on localhost:8080/metrics, so we'd need instructions on how to setup grafana at a basic level, import that dashboard, and hook it up to the node's prometheus endpoint.

**Comment by PandaWhisperer** [comment]
Someone wrote up instructions (and some sample dashboards) here: https://github.com/GuillaumeMiralles/prysm-grafana-dashboard

Maybe this could serve as a starting point for this ticket?
