### ISSUE TITLE
Configuring a Fee Recipient Address parameters clarification needed

### ISSUE THREAD

**Issue by perci** [prysmaticlabs/documentation#447]
In https://docs.prylabs.network/docs/execution-node/fee-recipient (https://github.com/prysmaticlabs/documentation/tree/master/website/docs/execution-node/fee-recipient.md), both the parameters suggested-fee-recipient and fee-recipient-config-file have the note that says "This setting overrides the two config options below. If you set this, the config options will be ignored."  It's unclear which overrides when both are set.

**Comment by james-prysm** [comment]
this has been updated, now instead it's called the proposer-settings-file or proposer settings-url. this will override the suggested-fee-recipient.

**Comment by symbolpunk** [comment]
Thanks for submitting this @perci - closing as resolved. Feel free to reopen if needed.
