### ISSUE TITLE
Add Comprehensive Go+ Contributing Coding Guidelines for Prysm

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/documentation#45]
We should have a dedicated page that is thorough regarding Go guidelines for Prysm developers, along with testing standards for anyone contributing to the repository.

**Comment by har00ga** [comment]
Noted. Testing standards are definitely not currently present, but there is this: https://docs.prylabs.network/docs/contribute/golang-principles/

thoughts on where to expand?

**Comment by rauljordan** [comment]
We have decided to this in our developer wiki, our teammate Radek started work on this
