### ISSUE TITLE
Docs update request: /docs/advanced/maintaining-uptime

### ISSUE THREAD

**Issue by cyruskarsan** [prysmaticlabs/documentation#538]
Source: https://docs.prylabs.network/docs/advanced/maintaining-uptime

Request: (how can we help?)
The link to `check software status` is broken. 

A few improvements to the systemd configuration. 

- After should be `network-online.target` since we want beacon-chain to start after an internet connection has been established. 
- WantedBy should be `default.target` there is no `multi-user.target` in a user's systemd manager.
- (Optional) restart-on should probably be `on-failure`

Here's my config file. 

```
[Unit]
Description=Prysm Beacon chain daemon
After=network-online.target

[Service]
ExecStart=/home/staker/ethereum/consensus/prysm/prysm.sh beacon-chain --config-file /home/staker/ethereum/consensus/prysm/eth1.yaml
Restart=on-failure
User=staker

[Install]
WantedBy=default.target
```

**Comment by mick-prysm** [comment]
Hi @cyruskarsan would you mind confirming that the link to `check software status` is still broken on your end? I'm unable to repro.

If it's still broken, can you share the URL that you see after clicking? Thank you!

**Comment by mick-prysm** [comment]
Your suggestion was merged in - thanks again @cyruskarsan  🙏
