### ISSUE TITLE
Docs update request: /docs/monitoring/checking-status

### ISSUE THREAD

**Issue by cyruskarsan** [prysmaticlabs/documentation#539]
Source: https://docs.prylabs.network/docs/monitoring/checking-status

Suggestion: pipe curl results to jq. Will make the output a lot more human readable. 

Example:
`curl http://localhost:3500/eth/v1/node/syncing | jq`

**Comment by mick-prysm** [comment]
Thanks for this @cyruskarsan - this has been incorporated via https://github.com/prysmaticlabs/documentation/pull/547. Appreciate your support, happy staking :)
