### ISSUE TITLE
Docs update request: /docs/prepare-for-merge

### ISSUE THREAD

**Issue by RobertClarke** [prysmaticlabs/documentation#543]
Source: https://docs.prylabs.network/docs/prepare-for-merge

Request: Could you clarify if an eth1 light node is sufficient or if a full node is required to operate alongside a beaconchain node/validator pair.

**Comment by mick-prysm** [comment]
Thanks for submitting this issue @RobertClarke! Fixed by https://github.com/prysmaticlabs/documentation/pull/546. Happy staking :)
