### ISSUE TITLE
Docs update request: /docs/prepare-for-merge: add information for Erigion as EC

### ISSUE THREAD

**Issue by mondsen** [prysmaticlabs/documentation#592]
Source: https://docs.prylabs.network/docs/prepare-for-merge

Request: It would be helpful to include a documentation for Erigon as execution client.

**Comment by mick-prysm** [comment]
Thanks for submitting this, @mondsen. Erigon is still in alpha, so I'm going to close this as a #wontfix for now - we plan to include Erigon once they move from alpha -> beta -> stable GA.
