### ISSUE TITLE
Docs update request: /docs/prysm-usage/checkpoint-sync

### ISSUE THREAD

**Issue by muang0** [prysmaticlabs/documentation#594]
Source: https://docs.prylabs.network/docs/prysm-usage/checkpoint-sync

Request: (how can we help?)

Capturing szz state and block for checkpoint-sync doesn't actually require Go if you call the prysm api directly.  Can we update the doc to reflect this?  Happy to contribute this change myself, I'll wait on green-light comment from a contributor.

https://github.com/prysmaticlabs/documentation/blob/master/website/docs/prysm-usage/checkpoint-sync.md?plain=1#L72-L76

**Comment by mick-prysm** [comment]
Thanks very much @muang0 - absolutely feel free to submit a docs PR! Very kind of you to offer. I'll include @kasey in the PR review - he's our resident checkpoint sync SME :)

**Comment by mick-prysm** [comment]
https://github.com/prysmaticlabs/documentation/pull/598#issuecomment-1234267598 elaborates on a current limitation + plans to improve this UX. I'll close this issue but please don't hesitate to reopen if there's a misunderstanding. Thank you again :)
