### ISSUE TITLE
Docs update request: /docs/prepare-for-merge

### ISSUE THREAD

**Issue by mazurroman** [prysmaticlabs/documentation#595]
Source: https://docs.prylabs.network/docs/prepare-for-merge

# Request:

3rd item in the checklist states:

`Verify that you're running Prysm v3.0.0 by issuing the following command: prysm.sh beacon-chain --version (Linux) prysm.bat beacon-chain --version (Windows).`

If my understanding is correct, starting with prysm v3.0.0, there is no single `prysm.sh` script but two separate scripts: `validator` and `beacon-chain`. The way to check the version would hence be `./validator --version` and `./beacon-chain --version`, instead of `./prysm.sh validator --version` or `./prysm.sh beacon-chain --version`

**Comment by mick-prysm** [comment]
Thanks @mazurroman - `prysm.sh/bat` ships with our releases (including 3.0/3.1). It's basically a "magic script" that downloads the binaries and allows the user to interact with them. 

I believe if you manually build the binaries (eg using Bazel) you can invoke `validator` and `beacon-chain` as you suggest, but many (if not most) users will be using the script. Let me know if I've misunderstood anything, happy to reopen if so. Thanks again for submitting the suggestion 🙏
