### ISSUE TITLE
"How Prysm works" links are broken

### ISSUE THREAD

**Issue by edo3** [prysmaticlabs/documentation#62]
Most links are misaligned, resulting in broken links. I'll provide a few examples.

On https://docs.prylabs.network/docs/how-prysm-works/architecture-overview/:

- "this section" is: https://docs.prylabs.network/docs/how-prysm-works/introduction/ethereum-2.0 should be: https://docs.prylabs.network/docs/introduction/on-ethereum-2/
- "proof-of-stake validators is: https://docs.prylabs.network/docs/glossaries/terminology#proof-of-stake-pos should be: https://docs.prylabs.network/docs/terminology/#validator
- Others links on the page are also not working

On https://docs.prylabs.network/docs/how-prysm-works/beacon-node/:
- "proof-of-stake" is: https://docs.prylabs.network/docs/glossaries/terminology#proof-of-stake-pos should be: https://docs.prylabs.network/docs/terminology/#proof-of-stake-pos
- "proposal" is: https://docs.prylabs.network/docs/glossaries/terminology#propose should be: https://docs.prylabs.network/docs/terminology/#proposal-propose-a-idproposea
- "attested", "validators" and others are broken too.

Other pages are probably broken too.

**Comment by har00ga** [comment]
#63 Solves this, thanks again
