### ISSUE TITLE
Docs update request: /docs/troubleshooting/issues-errors

### ISSUE THREAD

**Issue by axing1991** [prysmaticlabs/documentation#630]
Source: https://docs.prylabs.network/docs/troubleshooting/issues-errors

Request: (how can we help?)  

eacon client online, but never received consensus updates. Please ensure your beacon client is operational to follow the chain!

**Comment by mick-prysm** [comment]
Thanks @axing1991 - it looks like your beacon node needed more time to sync. The docs have been updated to include this scenario-solution mapping via https://github.com/prysmaticlabs/documentation/pull/644. 

If you're still experiencing issues, would you mind reaching out on Discord for troubleshooting support? Thank you!
