### ISSUE TITLE
attestations fail Docs update request: /docs/troubleshooting/issues-errors

### ISSUE THREAD

**Issue by ric2020stake** [prysmaticlabs/documentation#631]
Source: https://docs.prylabs.network/docs/troubleshooting/issues-errors

Request: the attestations is failing

**Comment by mick-prysm** [comment]
Hi @ric2020stake - if you're still experiencing this issue, would you mind reaching out on Discord for troubleshooting support? The `Request an update` button is for content update requests. Thank you!
