### ISSUE TITLE
after initial sync state my  geth version 23 node goes state heal in progress

### ISSUE THREAD

**Issue by hashcashconsultant** [prysmaticlabs/documentation#634]
after initial sync state my  geth version 23 node goes state heal in progress how much time its will take to completed

**Comment by mick-prysm** [comment]
Thanks @hashcashconsultant - it should take less than a day, usually less than a couple hours if using an SSD. The docs have been updated to address this question via https://github.com/prysmaticlabs/documentation/pull/645. Thanks again!
