### ISSUE TITLE
Docs update request: /docs/install/install-with-script

### ISSUE THREAD

**Issue by tjayrush** [prysmaticlabs/documentation#637]
Source: https://docs.prylabs.network/docs/install/install-with-script

Request: (how can we help?)

I am running Prysm on a Mac M1 machine. I don't think this line in your docs is valid:

```
Can I use Prysm on a Mac M1 ARM chip?
Mac M1 ARM chips currently require users to run Prysm through [Rosetta](https://support.apple.com/en-us/HT211861). See our [open bug](https://github.com/prysmaticlabs/prysm/issues/9385) for details.
```

I was told I could start Prysm with this environment variable:

```
export PRYSM_ALLOW_UNVERIFIED_BINARIES=1
```

and I did so, and it works fine for many weeks already.

Suggestion: replace the above text in your help document with instructions to add the environment variable (assuming that is the correct way to do things now).

**Comment by mick-prysm** [comment]
Thanks again - closing as resolved via https://github.com/prysmaticlabs/documentation/pull/643
