### ISSUE TITLE
Docs update request: /docs/prysm-usage/individual-validator-monitoring

### ISSUE THREAD

**Issue by Dimasin** [prysmaticlabs/documentation#640]
Source: https://docs.prylabs.network/docs/prysm-usage/individual-validator-monitoring

Request: (how can we help?)

**Comment by Dimasin** [comment]
This not worked with beacon-chain version Prysm/v3.1.1/653ea3b030c3bb99aa3f3d95a8de9f4d6e147930

**Comment by prestonvanloon** [comment]
@Dimasin What was the result that you received? What did not work?

**Comment by Dimasin** [comment]
the flag `--monitor-indices` not work in beacon-chain version Prysm/v3.1.1/653ea3b030c3bb99aa3f3d95a8de9f4d6e147930
I use flag with any number, e.g. "beacon-chain --monitor-indices 1" and dont see a message like the following in logs at launch `INFO monitor: "Starting service" ValidatorIndices="[1]"`

**Comment by mick-prysm** [comment]
Thanks @Dimasin - https://github.com/prysmaticlabs/prysm/issues/11532 has been created to track this on the dev side. I'll keep this open for now in case docs need to be updated (eg maybe `monitor` outputs aren't emitted until certain conditions are met).

**Comment by james-prysm** [comment]
closing as related issue was closed.
