### ISSUE TITLE
Docs update request: /docs/monitoring/checking-status

### ISSUE THREAD

**Issue by lanephillips** [prysmaticlabs/documentation#648]
Source: https://docs.prylabs.network/docs/monitoring/checking-status

Request: `geth attach` fails on testnet.

If I simply type `geth attach` as suggested by this document, it returns the error message: "Fatal: Unable to attach to remote geth: dial unix /home/me/.ethereum/geth.ipc: connect: no such file or directory", probably because the .ipc file is actually in .ethereum/goerli/geth.ipc

If instead I do `geth attach http://localhost:8545`, then it works.

**Comment by mick-prysm** [comment]
Thanks very much for the heads up @lanephillips - fixed via https://github.com/prysmaticlabs/documentation/pull/650.
