### ISSUE TITLE
Docs update request: /docs/how-prysm-works/architecture-overview

### ISSUE THREAD

**Issue by chhangloun-invest** [prysmaticlabs/documentation#651]
Source: https://docs.prylabs.network/docs/how-prysm-works/architecture-overview?utm_campaign=

**Comment by clarin-dy** [comment]
Hi @chhangloun-invest! I'm going to close this update request because it doesn't contain a specific request; please feel free to either resubmit a more detailed request or update the issue with details and I can reopen :) Thank you for your support!
