### ISSUE TITLE
Building in release mode on MacOS

### ISSUE THREAD

**Issue by nalepae** [prysmaticlabs/documentation#656]
[Documentation](https://docs.prylabs.network/docs/install/install-with-bazel#install-prysm-using-bazel) states:

```
bazel build //cmd/beacon-chain:beacon-chain --config=release
bazel build //cmd/validator:validator --config=release
```

However, trying it on MacOS ends up with the following error message:
```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from external/herumi_mcl/src/bn_c384_256.cpp:6:
In file included from external/herumi_mcl/include/mcl/impl/bn_c_impl.hpp:13:
In file included from external/herumi_mcl/include/mcl/bls12_381.hpp:11:
In file included from external/herumi_mcl/include/mcl/bn.hpp:11:
In file included from external/herumi_mcl/include/mcl/fp_tower.hpp:9:
In file included from external/herumi_mcl/include/mcl/fp.hpp:29:
In file included from external/herumi_mcl/include/mcl/op.hpp:9:
external/herumi_mcl/include/mcl/gmp_util.hpp:37:10: fatal error: 'gmpxx.h' file not found
```

Googling indicates to solve it:
```
brew install gmp
```

which does **not** solve the issue.

In Prysm Ethereum Client discord, we find [this message](https://discord.com/channels/476244492043812875/476588476393848832/1016599711324573717).

![image](https://user-images.githubusercontent.com/4943830/198021922-bad5e219-2742-41bc-b912-5d486bd905e0.png)

```
bazel build //cmd/beacon-chain:beacon-chain
bazel build //cmd/validator:validator
```

(without `--config=release`) works well.

Maybe the documentation could state:
- building in release mode is not possible on MacOS, or
- a way to install correctly `gmpxx.h` on MacOS

**Comment by james-prysm** [comment]
I think this should have been resolved.
