### ISSUE TITLE
Docs update request: /docs/monitoring/checking-status

### ISSUE THREAD

**Issue by StormeNet** [prysmaticlabs/documentation#679]
Source: https://docs.prylabs.network/docs/monitoring/checking-status

Request: The part for nethermind for checking sync status with curl (curl localhost:8545/health) doesn't work.
I found that the following does work:
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}'  127.0.0.1:8545

**Comment by james-prysm** [comment]
I believe docs have been updated since then. 3500 would be the http port which may have caused your issue.
