### ISSUE TITLE
Docs update request: /docs/troubleshooting/issues-errors

### ISSUE THREAD

**Issue by Manoj-noborders** [prysmaticlabs/documentation#688]
Source: https://docs.prylabs.network/docs/troubleshooting/issues-errors

Request: (how can we help?)
getting this issue 
time="2023-01-03 14:06:25" level=info msg="Synced new block" block=0xe652dc4b... epoch=171685 finalizedEpoch=171683 finalizedRoot=0x2ab7a93e... prefix=blockchain slot=5493930
time="2023-01-03 14:06:25" level=info msg="Finished applying state transition" attestations=128 payloadHash=0x91b5f3fe18d9 prefix=blockchain slot=5493930 syncBitsCount=505 txCount=198
time="2023-01-03 14:06:34" level=info msg="Falling back to historical headers and logs sync. Current difference is 518" prefix=powchain
time="2023-01-03 14:06:34" level=error msg="Could not process deposit log: received incorrect merkle index: wanted 506610 but got 507004" prefix=powchain

**Comment by clarin-dy** [comment]
Hi @Manoj-noborders Which execution client are you using?

**Comment by james-prysm** [comment]
stale reach out on discord.
