### ISSUE TITLE
Docs update request: /docs/how-prysm-works/validator-lifecycle

### ISSUE THREAD

**Issue by samlaf** [prysmaticlabs/documentation#694]
Source: https://docs.prylabs.network/docs/how-prysm-works/validator-lifecycle

Request: (how can we help?)

The minimum 9 days active before being allowed to exit is wrong I believe.
At least the phase0 consensus spec lists for [voluntary_exits](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#voluntary-exits):
```assert get_current_epoch(state) >= validator.activation_epoch + SHARD_COMMITTEE_PERIOD```
And `SHARD_COMMITTEE_PERIOD` = 256 epochs ~= 27 hours

**Comment by james-prysm** [comment]
I'll look at updating this
