### ISSUE TITLE
Request: Include info about debug images

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/documentation#7]
As of https://github.com/prysmaticlabs/prysm/pull/4893, we now provide debug images for the beacon-chain and validator docker images.

Many advanced users have asked for basic tooling that comes with the [Busybox](https://en.wikipedia.org/wiki/BusyBox) base image. Specifying docker images with a `-debug` suffix will now include that tooling.

**Comment by har00ga** [comment]
fa3392b Added. Sorry about the wait! :heartbeat:
