### ISSUE TITLE
Add a build test to check for broken links

### ISSUE THREAD

**Issue by wgknowles** [prysmaticlabs/documentation#70]
Changes in site topology or titles can result in broken links throughout the docs.  Include a automatic test for broken links using: https://github.com/stevenvachon/broken-link-checker

**Comment by har00ga** [comment]
Docusaurus' already print out a list of unresolved links on static build

**Comment by prestonvanloon** [comment]
Can we add this to our CI pipeline? 

Let me know it works and I can add something to fail PRs if they break links

**Comment by har00ga** [comment]
Reopening as we've experienced issues with docusaurus link debugging feature

**Comment by prestonvanloon** [comment]
How does the link debugging work? Can we add it to CI pipeline?

**Comment by prestonvanloon** [comment]
Ping @har00ga

**Comment by prestonvanloon** [comment]
Another broken link: https://github.com/prysmaticlabs/documentation/pull/94

**Comment by har00ga** [comment]
Oh sorry, didnt see this notification. From what I gather it's something that can be run on a live site or hard coded into the docs themselves to have the checks performed, not sure which is ultimately simpler but if I had to guess, the live scan. It can likely be run against the live server and links can be checked before every revision push

**Comment by prestonvanloon** [comment]
Relevant issue: https://github.com/facebook/Docusaurus/issues/1111 

The idea would be that we run this check on a new PR and fail that PR if it is breaking links. Running a live server doesn't seem viable in CI unless there is some example of it already.

**Comment by wgknowles** [comment]
Broken link checker works a treat!

Sample extract of output:
```
blc http://localhost:3000/ -roe
Getting links from: http://localhost:3000/docs/how-prysm-works/bls-cryptography
├─BROKEN─ http://localhost:3000/docs/glossaries/terminology.md#proof-of-stake-pos (HTTP_404)
├─BROKEN─ http://localhost:3000/docs/glossaries/terminology.md#validator (HTTP_404)
├─BROKEN─ http://localhost:3000/docs/glossaries/terminology.md#proof-of-stake-pos (HTTP_404)
├─BROKEN─ http://localhost:3000/docs/glossaries/terminology.md#validator (HTTP_404)
Finished! 77 links found. 73 excluded. 4 broken.
Finished! 3774 links found. 3719 excluded. 4 broken.```

**Comment by har00ga** [comment]
@prestonvanloon Works for me, would be awesome to implement that if possible. Seeing as it works on the live server as well it would be good to make a note in the README that contributors should use the link tool before submitting a PR to reduce friction at merge time

**Comment by har00ga** [comment]
#101 Link checking to be included as a step in this

**Comment by prestonvanloon** [comment]
If someone can help implement this as a github action, we could add it as a PR requirement.

**Comment by har00ga** [comment]
@prestonvanloon Haven't worked with GH Actions before but will read into it this week

**Comment by har00ga** [comment]
#175
