### ISSUE TITLE
Docs update request: /docs/troubleshooting/issues-errors/

### ISSUE THREAD

**Issue by Piyushmethi09** [prysmaticlabs/documentation#705]
Source: https://docs.prylabs.network/docs/troubleshooting/issues-errors/

**Comment by clarin-dy** [comment]
Hi @Piyushmethi09! I'm going to close this update request because it doesn't contain a specific request; please feel free to either resubmit a more detailed request or update the issue with details and I can reopen :) Thank you for your support!
