### ISSUE TITLE
Docker image for prysmctl not available

### ISSUE THREAD

**Issue by ArturDolzan** [prysmaticlabs/documentation#729]
# 🐞 Bug Report

### Description

Going through documentation, the command to exit a validator using docker: 

```
docker run -it -v $HOME/Eth2Validators/prysm-wallet-v2:/wallet \
  gcr.io/prysmaticlabs/prysm/prysmctl:latest \
  validator exit --wallet-dir=/wallet --beacon-rpc-provider=<127.0.0.1:4000> 
```

The issue is that the image is not available for pulling:

`docker image pull gcr.io/prysmaticlabs/prysm/prysmctl:latest`
output:
`Error response from daemon: manifest for gcr.io/prysmaticlabs/prysm/prysmctl:latest not found: manifest unknown: Failed to fetch "latest" from request "/v2/prysmaticlabs/prysm/prysmctl/manifests/latest".`

**Comment by nisdas** [comment]
@ArturDolzan The correct url for prysmctl would be `gcr.io/prysmaticlabs/prysm/cmd/prysmctl:latest` , however we should fix this in our docs

**Comment by ArturDolzan** [comment]
Thanks for your reply @nisdas. 
Now using the correct url (gcr.io/prysmaticlabs/prysm/cmd/prysmctl:latest) I've tried to call validator exit (same command from my first comment on this issue) and I got:

`No help topic for 'validator exit'`

Is this not available yet?

**Comment by james-prysm** [comment]
@ArturDolzan there should be help on that command... I'll fix the link apologies
