### ISSUE TITLE
Make keywallet manager warning clearer 

### ISSUE THREAD

**Issue by har00ga** [prysmaticlabs/documentation#73]
Needs to be made clearer that the linked guide is still available and supported (but given its third party can still not be fully recommended for production)

**Comment by Alko89** [comment]
Would changing the first sentence to 

  >As Prysmatic Labs cannot maintain nor endorse third party tools used to manage keys, this guide is no longer maintained and **is not recommended for production use**.

Make it clear enough?

**Comment by har00ga** [comment]
Sorted :slightly_smiling_face: #82
