### ISSUE TITLE
Docs update request: /docs/advanced/proof-of-stake-devnet

### ISSUE THREAD

**Issue by xinwwx** [prysmaticlabs/documentation#742]
Source: https://docs.prylabs.network/docs/advanced/proof-of-stake-devnet

Request: (how can we help?)
 error="could not set config params: config name=devnet conflicts with existing config named=mainnet: configset cannot add config with conflicting fork version schedule" prefix=genesis

**Comment by james-prysm** [comment]
config issues, docs will be updated to improve devnet settings
