### ISSUE TITLE
Docs update request: /docs/advanced/proof-of-stake-devnet

### ISSUE THREAD

**Issue by avenbreaks** [prysmaticlabs/documentation#743]
Source: https://docs.prylabs.network/docs/advanced/proof-of-stake-devnet

Request: (how can we help?)
update the devnet documentation, one of your docker is not working

**Comment by avenbreaks** [comment]
@symbolpunk 

i see : error="could not set config params: config name=devnet conflicts with existing config named=mainnet: configset cannot add config with conflicting fork version schedule" prefix=genesis

**Comment by trivonhan** [comment]
> 

+1

**Comment by james-prysm** [comment]
I believe it was updated but let us know if it isn't https://github.com/OffchainLabs/eth-pos-devnet

**Comment by james-prysm** [comment]
stale
