### ISSUE TITLE
Docs update request: /docs/how-prysm-works/validator-lifecycle

### ISSUE THREAD

**Issue by QlDoors** [prysmaticlabs/documentation#748]
Source: https://docs.prylabs.network/docs/how-prysm-works/validator-lifecycle

Request: (how can we help?)
![validator lifecycle](https://docs.prylabs.network/assets/images/validator-lifecycle-0e764e64209fa197a59600eb28766368.png)
The validator lifecycle illustration contains an error. In the image, the delay from the depositing state to hanging is depicted as "EPOCHS_PER_ETH1_VOTING_PERIOD + EPOCHS_PER_ETH1_VOTING_PERIOD", which is incorrect. The accurate delay should be represented as "ETH1_FOLLOW_DISTANCE + EPOCHS_PER_ETH1_VOTING_PERIOD".

**Comment by james-prysm** [comment]
you're right! will fix that
