### ISSUE TITLE
Docs update request: /docs/wallet/withdraw-validator

### ISSUE THREAD

**Issue by sneaker1** [prysmaticlabs/documentation#771]
Source: https://docs.prylabs.network/docs/wallet/withdraw-validator

Request: (how can we help?)

The docker command to make the blstoexecutionchange with prysmctl contains a non existing image.
The prysmctl image actually is under the cmd subfolder.

Currently the command in the withdrawal guide is:
```
docker run -it -v $HOME/path/to/bls_to_execution:/bls_dir \
  gcr.io/prysmaticlabs/prysm/prysmctl:latest \
  validator withdraw -beacon-node-host=<node-url> --path=/bls_dir
```

The correct command with the correct image should be:
```
docker run -it -v $HOME/path/to/bls_to_execution:/bls_dir \
  gcr.io/prysmaticlabs/prysm/cmd/prysmctl:latest \
  validator withdraw -beacon-node-host=<node-url> --path=/bls_dir
```

**Comment by james-prysm** [comment]
thanks for the catch 🙏
