### ISSUE TITLE
Docs update request: /docs/wallet/exiting-a-validator

### ISSUE THREAD

**Issue by AegeanDad** [prysmaticlabs/documentation#772]
Source: https://docs.prylabs.network/docs/wallet/exiting-a-validator

Request: Please do not deprecate the validator exit procedure using the "prysm.sh validator accounts voluntary-exit" without coordinating with the likes of Coincashew and Somer. They are still referring to the old method. I am sure you have your reasons but your instructions here, particularly those that pertain to cloning the Prysm Git repository and building prysmctl from source are not very user friendly and cloning fails because the prysm directory already exists. People like me who are not native OS gurus rely on these guides to manage these types of things.  

I care because I document this particular procedure for my heirs in case something were to happen to me and voluntary-exit procedure is much easier to follow for novices.

**Comment by james-prysm** [comment]
If you feel that any of our own documents can further clarify things please help us by opening a PR adding improvements to the docs

**Comment by james-prysm** [comment]
closing due to staleness, again please help us by opening a PR
