### ISSUE TITLE
Docs update request: /docs/troubleshooting/issues-errors

### ISSUE THREAD

**Issue by farhanakottal** [prysmaticlabs/documentation#823]
Source: https://docs.prylabs.network/docs/troubleshooting/issues-errors

Request: 
I was running private chain on geth withPoS, but cannot initialize beacon-node using custom network.

prysm:
prysm beacon-chain --chain-config-file config.yaml --genesis-state genesis.json

output:
WARN flags: Running on custom Ethereum network specified in a chain configuration yaml file
config name=devnet conflicts with existing config named=mainnet: configset cannot add config with conflicting fork version schedule
ERROR FAILED
an error has occured, set PRYSM_AUTORESTART=1 to automatically restart

**Comment by james-prysm** [comment]
stale
