### ISSUE TITLE
Links Broken in "Activating a Validator" Prysm documentation

### ISSUE THREAD

**Issue by ekbyang** [prysmaticlabs/documentation#83]
In the [Activating a Validator](https://docs.prylabs.network/docs/install/mac/activating-a-validator/) portion of the documentation, the following links in "Step 1" are currently broken:

- https://docs.prylabs.network/docs/install/mac/mac
- https://docs.prylabs.network/docs/install/mac/activating-a-validator/docker
- https://docs.prylabs.network/docs/install/mac/activating-a-validator/bazel

**Comment by har00ga** [comment]
Thanks a bunch :)
