### ISSUE TITLE
Docs update request: /docs/advanced/proof-of-stake-devnet

### ISSUE THREAD

**Issue by dewindtk** [prysmaticlabs/documentation#850]
Source: https://docs.prylabs.network/docs/advanced/proof-of-stake-devnet

Request: 
There is an error preventing the create-beacon-chain-genesis-1 container from running.
Please review and update this page.

**Comment by james-prysm** [comment]
proof of stake devnet docs have been updated a bit since then, closing for staleness, devnet docs will continue to update as we review issues and requests.
