### ISSUE TITLE
Docs update request: /docs/prysm-usage/checkpoint-sync

### ISSUE THREAD

**Issue by mbwmbw1337** [prysmaticlabs/documentation#854]
Source: https://docs.prylabs.network/docs/prysm-usage/checkpoint-sync

Request: The links to verify the slot no longer work. Please fix.

**Comment by james-prysm** [comment]
you need to replace the slot with the number for it to work , tested , seems to be working ( you are referring to the beaconcha.in links I assume)

**Comment by mbwmbw1337** [comment]
Yes thakn you!
