### ISSUE TITLE
Docs update request: /docs/advanced/switch-clients

### ISSUE THREAD

**Issue by defeedme** [prysmaticlabs/documentation#891]
i'm running windows with nethermind and i'm losing peers every few hours, very frustrating and i know my ports are open I tested them with  https://mxtoolbox.com/SuperTool.aspx?action=tcp%3a24.189.113.188%3a13000&run=toolpage

I've been running fine since genesis for 3 years and all of a sudden this is happening 4.1.1
I see in your instructions you do mention there's a "bug" in your own software causing windows users to lose peers and you even recommend downgrading! wow

so I need better instructions and which other validator client is best for windows.. thanks

Source: https://docs.prylabs.network/docs/advanced/switch-clients

Request: (how can we help?)

**Comment by james-prysm** [comment]
I believe lighthouse may support windows as well as teku but mostly not maintained, hopefully some of your issues will be resolved our next release. I can't speak to or recommend which client to switch to, perhaps you can try a few yourself. I only know that lodestar doesn't seem to support windows.

**Comment by defeedme** [comment]
thanks I'm waiting with baited breadth for the next revision, in the meantime I'm constantly stopping and restarting prysm to find peers and it works for a few hours then fails miserably..  i'm leaning towards nimbus at this point.. prysm worked great for 3 years, what happened?

**Comment by james-prysm** [comment]
Talking with team mates it seems windows users have experienced lost packets before ( somewhat related experience https://github.com/prysmaticlabs/prysm/issues/8144) There hasn't been anything specific done in prysm to lose support and we haven't heard any other reports from windows users besides the yours that was mentioned.

**Comment by defeedme** [comment]
bizarre then, my system worked fine for 3 years and now it just looses peers after about 2 hours... I had to setup a schedule task to kill beacon and restart it every 2 hours..  version 4.2 hasn't changed anything for windows

**Comment by james-prysm** [comment]
added information on time drift

**Comment by theandygould** [comment]
Is there any update on this? I'm having the same issue and it's simply infuriating

**Comment by prestonvanloon** [comment]
@justaguy24 Track the issue here: https://github.com/prysmaticlabs/prysm/issues/13936
