### ISSUE TITLE
Docs update request: /docs/prysm-usage/prysmctl

### ISSUE THREAD

**Issue by chimera-defi** [prysmaticlabs/documentation#911]
Source: https://docs.prylabs.network/docs/prysm-usage/prysmctl

Request: 

Howdy! Happy 2024. 

Would it be possible to add the Ubuntu install link for bazel to the docs?
Add ` Using apt: https://bazel.build/install/ubuntu` 
After the line saying `Using npm:` 
for example. 

## Rationale
Imo a lot of users will be running the prysmctl tool on the node running the validators as it needs access to the exec API and a open RPC url may not work.  
E.g i get this error using the `rpc.sharedtools.org/rpc`, running an rpc with prysm, nginx, geth with SSL.  
```
FATA[0001] Could not set withdrawal addresses            error="could not retrieve current fork information: error requesting fork by state id = head: code=404, url=https://rpc.sharedtools.org/eth/v1/beacon/states/head/fork, body=response body:\n<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n: recv 404 NotFound response from API: did not receive 2xx response from API"
```

With ubuntu being the most common distro, theres a high chance that the user will need ubuntu install instructions. 

The apt suggestion of `apt install bazel-bootstrap` or the bazel error suggestions of `apt install bazel-7.0.0` did not work for me. 
But the steps in the URL i linked did work! 

Cheerio,
Chimera

**Comment by james-prysm** [comment]
added
