### ISSUE TITLE
Beacon Chain API data is not available    /eth/v1/beacon/blob_sidecars/{block_id}

### ISSUE THREAD

**Issue by ZYS980327** [prysmaticlabs/documentation#934]
I use prysmrpc data to build the L2 chain, when I call the /eth/v1/beacon/blob_sidecars/{block_id} method, sometimes I can't get the data, resulting in I can't build a node, but I get the data when I use the quicknodeApi call, we should fix this problem, it may be a problem caused by the hard fork, how can I fix the data in this api

**Comment by prestonvanloon** [comment]
Not sure what your request is here. If you have an issue with Prysm, please file that in the prysm repository instead of the docs repo.
